stages:
  - test
  # - build_push
  - deploy

before_script:
  - cd hcare-backend/
  - chmod +x ./init.sh
  - ./init.sh
  - mv .env.docker .env
  # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

test:
  stage: test
  only:
    - merge_requests
  script: 
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:develop .
    - docker run -d -p 33972:3333 --name hcare_adonis-dev --env-file .env --restart=always $CI_REGISTRY_IMAGE:develop

# build-push-image:
#   stage: build_push
#   only:
#     - tags
#   except:
#     - branches
#   script:
#     - docker-compose build adonis
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#     - "Build Adonis is done"

deploy-prod-adonis:
  stage: deploy
  only:
    - tags
  except:
    - branches
  script:
    - docker kill hcare_nginx hcare_adonis || true
    - docker rm hcare_nginx hcare_adonis || true
    - ls -la
    - docker-compose up -d --build
  when: manual

# deploy-prod-all:
#   stage: deploy
#   only:
#     - master
#   script:
#     - docker-compose up -d --build
#   when: manual

after_script:
  - docker ps
