stages:
  - build
  - deploy
  - tags_push

before_script:
  - cd hcare-backend/
  - chmod +x ./init.sh
  - ./init.sh
  - mv .env.docker .env

##########  -  develop  -  ##########
build-image-develop:
  stage: build
  only:
    - develop
  script:
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:develop .

deploy-develop:
  stage: deploy
  only:
    - develop
  script:
    - docker rm -f hcare_adonis-dev || true
    - docker run -d -p 33972:3333 --name hcare_adonis-dev --env-file .env --restart=always $CI_REGISTRY_IMAGE:develop
  when: manual

##########  -  master  -  ##########
build-image-master:
  stage: build
  only:
    - master
  script:
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:latest .

deploy-master:
  stage: deploy
  only:
    - master
  script:
    - docker rm -f hcare_adonis || true
    - docker run -d -p 33971:3333 --name hcare_adonis --env-file .env --restart=always $CI_REGISTRY_IMAGE:latest
  when: manual

##########  -  tag  -  ##########
tags-push-image:
  stage: tags_push
  only:
    - tags
  except:
    - branches
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG


after_script:
  - docker ps
