version: "3.1"
services:
  ### NGINX #####################################
  nginx:
    image: nginx:1.17.8-alpine
    container_name: hcare_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      - ./www/:/usr/share/nginx/html
    restart: always
    networks:
      - api-network

  ### My SQL #####################################
  mysql:
    image: mysql:5.7
    container_name: hcare_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: Asia/Bangkok
    restart: always
    networks:
      - api-network

  ### ADONIS #####################################
  adonis:
    build: ./hcare-backend
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    container_name: hcare_adonis
    ports:
      - 3333:3333
    restart: always
    networks:
      - api-network

  ### PHPMYADMIN #####################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hcare_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

networks:
  api-network:
